### ISSUE TITLE
Android 启动后崩溃

### ISSUE THREAD

**Issue by kangfenmao** [haxibiao/react-native-ad#11]
--------- beginning of crash
2021-02-04 16:08:16.762 15215-15215/com.stonecutter.faceteng E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx, PID: 15215
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.haxifang.ad.activities.SplashActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.bytedance.sdk.openadsdk.TTAdNative.loadSplashAd(com.bytedance.sdk.openadsdk.AdSlot, com.bytedance.sdk.openadsdk.TTAdNative$SplashAdListener, int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.bytedance.sdk.openadsdk.TTAdNative.loadSplashAd(com.bytedance.sdk.openadsdk.AdSlot, com.bytedance.sdk.openadsdk.TTAdNative$SplashAdListener, int)' on a null object reference
        at com.haxifang.ad.activities.SplashActivity.loadSplashAd(SplashActivity.java:132)
        at com.haxifang.ad.activities.SplashActivity.onCreate(SplashActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)

**Comment by PBK-B** [comment]
@kangfenmao 能提供更多的信息嘛？比如说您是怎么使用开屏广告的。

**Comment by kangfenmao** [comment]
```js
import Splash from 'react-native-splash-screen'
import { ad } from 'react-native-ad'

showAd() {
    // if (__DEV__) {
    //   return Splash.hide()
    // }

    const splashAd = ad.startSplash({ appid: '5143312', codeid: '887434211', anim: 'none' })

    return new Promise(resolve => {
      splashAd.subscribe('onAdShow', e => {
        Splash.hide()
        console.log('广告开始显示监听', e)
        resolve(true)
      })
      splashAd.subscribe('onAdClose', event => {
        console.log('广告时间结束监听', event)
        Splash.hide()
      })
    })
  }
```

@PBK-B

**Comment by PBK-B** [comment]
> ```js
> 
>     return new Promise(resolve => {
>       splashAd.subscribe('onAdShow', e => {
>         Splash.hide()
>         console.log('广告开始显示监听', e)
>         resolve(true)
>       })
> ```

抱歉，新版本广告需要在启动之前调用 init 方法。我已经注意到文档还没更新了，稍后我会更新文档的。
请在使用之前合适的时机加上 ad.init 方法
```
// 启动前，初始化Ad
ad.init({
        appid: "11111111111",
}); 
```
