### ISSUE TITLE
react native v0.63.4 版本安装后无法运行

### ISSUE THREAD

**Issue by kangfenmao** [haxibiao/react-native-ad#20]
--------- beginning of crash
2021-04-30 11:56:12.129 10804-10804/com.stonecutter.faceteng E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.stonecutter.faceteng, PID: 10804
    java.lang.RuntimeException: Unable to get provider com.bytedance.sdk.openadsdk.TTFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTFileProvider" on path: DexPathList[[zip file "/data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/lib/arm64, /data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7194)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6672)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTFileProvider" on path: DexPathList[[zip file "/data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/lib/arm64, /data/app/com.stonecutter.faceteng-uf5Pmrf_96PmK4QBZqVE8g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7178)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6672) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:224) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by PBK-B** [comment]
@kangfenmao  注意： 对接 react-native-ad v1.1.5 及以上版本或 React Native v0.64.0 以上版本对接之后导致闪退的需参考：[React Native v0.64.0 Android 对接 sdk 过渡方案](https://github.com/haxibiao/react-native-ad/blob/master/docs/excessive_v1.16.md)
